### ISSUE TITLE
yahoo download intermittent failure

### ISSUE THREAD

**Issue by mathieugouin** [mathieugouin/tradesim#67]
github CI:

python 3.8

```
  # The 'empty' DB folder is always kept empty after each test.
  mkdir -p stock_db/empty
  # Append coverage (-a)
  # The 'test' DB folder contains a few symbols used during tests.
  python -m coverage run -a get_yahoo_finance_data.py --concurrent 1 --file stock_db/test.txt --dir ./stock_db/test --startdate 20100101 --verbose
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/mathieugouin/tradesim/actions/runs/6406454209/job/17391088892#step:8:3).8.18/x6[4](https://github.com/mathieugouin/tradesim/actions/runs/6406454209/job/17391088892#step:8:4)
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.8.18/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.18/x64/lib
Traceback (most recent call last):
  File "get_yahoo_finance_data.py", line 174, in <module>
    _main()
  File "get_yahoo_finance_data.py", line 1[5](https://github.com/mathieugouin/tradesim/actions/runs/6406454209/job/17391088892#step:8:5)0, in _main
    _my_assert(len(yqd.load_yahoo_quote('^GSPC', '20180212', '20180212')) > 5,
  File "/home/runner/work/tradesim/tradesim/yqd.py", line 71, in load_yahoo_quote
    _get_cookie_crumb()
  File "/home/runner/work/tradesim/tradesim/yqd.py", line 47, in _get_cookie_crumb
    f = urllib.request.urlopen(req, timeout=5)
  File "/opt/hostedtoolcache/Python/3.8.18/x[6](https://github.com/mathieugouin/tradesim/actions/runs/6406454209/job/17391088892#step:8:6)4/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/urllib/request.py", line 139[7](https://github.com/mathieugouin/tradesim/actions/runs/6406454209/job/17391088892#step:8:7), in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/hostedtoolcache/Python/3.[8](https://github.com/mathieugouin/tradesim/actions/runs/6406454209/job/17391088892#step:8:8).18/x64/lib/python3.8/urllib/request.py", line 1358, in do_open
    r = h.getresponse()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-885[9](https://github.com/mathieugouin/tradesim/actions/runs/6406454209/job/17391088892#step:8:9)-1")
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/ssl.py", line 1132, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
Command line options parsed successfully.
Skipping ticker file line: ################################################################################
Skipping ticker file line: # Udacity data
Skipping ticker file line: ################################################################################
Skipping ticker file line: # Symbol    Name
Adding AAPL from 20[10](https://github.com/mathieugouin/tradesim/actions/runs/6406454209/job/17391088892#step:8:10)0101 to [20](https://github.com/mathieugouin/tradesim/actions/runs/6406454209/job/17391088892#step:8:21)[23](https://github.com/mathieugouin/tradesim/actions/runs/6406454209/job/17391088892#step:8:24)1004
Adding GLD from 20100101 to 202[31](https://github.com/mathieugouin/tradesim/actions/runs/6406454209/job/17391088892#step:8:32)004
Adding GOOG from 20100101 to 20231004
Adding IBM from 20100101 to 20231004
Adding SPY from 20100101 to 20231004
Adding XOM from 20100101 to 20231004
----- Getting 6 tickers using 1 simultaneous connections -----
Downloading dummy quote...
Error: Process completed with exit code 1.
```

**Comment by mathieugouin** [comment]
To confirm if #73 fixes this.

**Comment by mathieugouin** [comment]
Does not reproduce
